{"ast":null,"code":"import _classCallCheck from\"C:\\\\Users\\\\Hovsep\\\\Desktop\\\\local\\\\diflow_react\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/classCallCheck\";import _createClass from\"C:\\\\Users\\\\Hovsep\\\\Desktop\\\\local\\\\diflow_react\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/createClass\";import _inherits from\"C:\\\\Users\\\\Hovsep\\\\Desktop\\\\local\\\\diflow_react\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/inherits\";import _createSuper from\"C:\\\\Users\\\\Hovsep\\\\Desktop\\\\local\\\\diflow_react\\\\node_modules\\\\babel-preset-react-app\\\\node_modules\\\\@babel\\\\runtime/helpers/esm/createSuper\";import React from'react';import{history}from'../../App';/** для редиректа на /auth при неотловленной ошибке */export var ErrorBoundary=/*#__PURE__*/function(_React$Component){_inherits(ErrorBoundary,_React$Component);var _super=_createSuper(ErrorBoundary);function ErrorBoundary(props){var _this;_classCallCheck(this,ErrorBoundary);_this=_super.call(this,props);_this.state={hasError:false};return _this;}_createClass(ErrorBoundary,[{key:\"render\",// componentDidCatch(error, errorInfo) {\n//   // Можно также сохранить информацию об ошибке в соответствующую службу журнала ошибок\n// }\nvalue:function render(){if(this.state.hasError){// history.push('/auth')\n}return this.props.children;}}],[{key:\"getDerivedStateFromError\",value:function getDerivedStateFromError(error){// Обновить состояние с тем, чтобы следующий рендер показал запасной UI.\nreturn{hasError:true};}}]);return ErrorBoundary;}(React.Component);","map":{"version":3,"sources":["C:/Users/Hovsep/Desktop/local/diflow_react/packages/app/src/common/error-boundary/ErrorBoundary.js"],"names":["React","history","ErrorBoundary","props","state","hasError","children","error","Component"],"mappings":"4pBAAA,MAAOA,CAAAA,KAAP,KAAkB,OAAlB,CACA,OAASC,OAAT,KAAuB,WAAvB,CAEA,sDACA,UAAaC,CAAAA,aAAb,0HACE,uBAAYC,KAAZ,CAAmB,+CACjB,uBAAMA,KAAN,EACA,MAAKC,KAAL,CAAa,CAAEC,QAAQ,CAAE,KAAZ,CAAb,CAFiB,aAGlB,CAJH,0CAWE;AACA;AACA;AAbF,uBAeW,CACP,GAAI,KAAKD,KAAL,CAAWC,QAAf,CAAyB,CACvB;AACD,CAED,MAAO,MAAKF,KAAL,CAAWG,QAAlB,CACD,CArBH,4EAMkCC,KANlC,CAMyC,CACrC;AACA,MAAO,CAAEF,QAAQ,CAAE,IAAZ,CAAP,CACD,CATH,2BAAmCL,KAAK,CAACQ,SAAzC","sourcesContent":["import React from 'react';\r\nimport { history} from '../../App'\r\n\r\n/** для редиректа на /auth при неотловленной ошибке */\r\nexport class ErrorBoundary extends React.Component {\r\n  constructor(props) {\r\n    super(props);\r\n    this.state = { hasError: false };\r\n  }\r\n\r\n  static getDerivedStateFromError(error) {\r\n    // Обновить состояние с тем, чтобы следующий рендер показал запасной UI.\r\n    return { hasError: true };\r\n  }\r\n\r\n  // componentDidCatch(error, errorInfo) {\r\n  //   // Можно также сохранить информацию об ошибке в соответствующую службу журнала ошибок\r\n  // }\r\n  \r\n  render() {\r\n    if (this.state.hasError) {\r\n      // history.push('/auth')\r\n    }\r\n\r\n    return this.props.children; \r\n  }\r\n}"]},"metadata":{},"sourceType":"module"}